# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/tmp.ljbuwFip2T

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/tmp.ljbuwFip2T/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/tmp.ljbuwFip2T/cmake-build-debug/CMakeFiles /tmp/tmp.ljbuwFip2T/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/tmp.ljbuwFip2T/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proj2

# Build rule for target.
proj2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proj2
.PHONY : proj2

# fast build rule for target.
proj2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/build
.PHONY : proj2/fast

help.o: help.c.o

.PHONY : help.o

# target to build an object file
help.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/help.c.o
.PHONY : help.c.o

help.i: help.c.i

.PHONY : help.i

# target to preprocess a source file
help.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/help.c.i
.PHONY : help.c.i

help.s: help.c.s

.PHONY : help.s

# target to generate assembly for a file
help.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/help.c.s
.PHONY : help.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/main.c.s
.PHONY : main.c.s

processes.o: processes.c.o

.PHONY : processes.o

# target to build an object file
processes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/processes.c.o
.PHONY : processes.c.o

processes.i: processes.c.i

.PHONY : processes.i

# target to preprocess a source file
processes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/processes.c.i
.PHONY : processes.c.i

processes.s: processes.c.s

.PHONY : processes.s

# target to generate assembly for a file
processes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/processes.c.s
.PHONY : processes.c.s

resources.o: resources.c.o

.PHONY : resources.o

# target to build an object file
resources.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/resources.c.o
.PHONY : resources.c.o

resources.i: resources.c.i

.PHONY : resources.i

# target to preprocess a source file
resources.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/resources.c.i
.PHONY : resources.c.i

resources.s: resources.c.s

.PHONY : resources.s

# target to generate assembly for a file
resources.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj2.dir/build.make CMakeFiles/proj2.dir/resources.c.s
.PHONY : resources.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... proj2"
	@echo "... help.o"
	@echo "... help.i"
	@echo "... help.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... processes.o"
	@echo "... processes.i"
	@echo "... processes.s"
	@echo "... resources.o"
	@echo "... resources.i"
	@echo "... resources.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

